---
- name: Package prerequisites for node.js
  apt: pkg={{ item }} state=installed
  with_items:
      - python-software-properties
      - make
      - g++

- name: Add the node.js PPA
  apt_repository: repo=ppa:chris-lea/node.js

- name: Update the apt cache for the new repository
  apt: update-cache=yes

- name: Install nodejs
  apt: pkg=nodejs state=installed

