---
- name: Package prerequisites for node.js
  apt: pkg={{ item }} state=installed
  with_items:
      - python-software-properties
      - make
      - g++

- name: Add nodejs repo key
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    state: present

- name: Add the node.js repo
  apt_repository:
    repo: "{{item}}"
    state: 'present'
    update_cache: yes
  with_items:
    - deb https://deb.nodesource.com/node_6.x {{ ansible_distribution_release|lower }} main
    - deb-src https://deb.nodesource.com/node_6.x {{ ansible_distribution_release|lower }} main

- name: Intsall build-essential
  apt: pkg=build-essential state=present

- name: Install nodejs
  apt: pkg=nodejs state=latest
